import type { Post, User, Donation } from "@/types";

export const DEMO_PASSWORD = "demo1234";

const av = (seed: string) => `/avatars/${seed}.svg`;

const daysAgo = (n: number) =>
  new Date(Date.now() - n * 86400000).toISOString();

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Оксана Мельник",
    email: "oksana@dii.ua",
    avatar: av("Oksana"),
    role: "organizer",
    karma: 542,
    location: "Київ",
    bio: "Координую гуманітарні ініціативи з 2022 року. Спеціалізуюсь на евакуації, продуктовій допомозі та координації з ЗСУ.",
    joinedAt: "2022-03-01",
    eventsParticipated: ["p1", "p3"],
    activeCollections: ["p2"],
    verified: true,
    isAdmin: true,
  },
  {
    id: "u2",
    name: "Андрій Коваль",
    email: "andriy@dii.ua",
    avatar: av("Andriy"),
    role: "volunteer",
    karma: 278,
    location: "Львів",
    bio: "Водій-волонтер. Маю Sprinter, готовий до далеких рейсів — гуманітарка, евакуація, медичні візити.",
    joinedAt: "2022-04-15",
    eventsParticipated: ["p1", "p4"],
    activeCollections: [],
  },
  {
    id: "u3",
    name: "Марія Ткач",
    email: "maria@dii.ua",
    avatar: av("Maria"),
    role: "organizer",
    karma: 712,
    location: "Харків",
    bio: "Медик-волонтер, сертифікований інструктор ТССС. Організовую закупівлі ліків та навчання першої допомоги.",
    joinedAt: "2022-02-25",
    eventsParticipated: ["p2", "p5"],
    activeCollections: ["p5"],
    verified: true,
  },
  {
    id: "u4",
    name: "Володимир Шевченко",
    email: "vova@dii.ua",
    avatar: av("Volodymyr"),
    role: "organizer",
    karma: 621,
    location: "Дніпро",
    bio: "Координатор гуманітарного хабу в Дніпрі. 4 роки у волонтерстві. Технічна допомога підрозділам.",
    joinedAt: "2021-11-10",
    eventsParticipated: [],
    activeCollections: [],
    verified: true,
  },
  {
    id: "u5",
    name: "Юлія Бондаренко",
    email: "yulia@dii.ua",
    avatar: av("Yulia"),
    role: "volunteer",
    karma: 195,
    location: "Одеса",
    bio: "Психолог, працюю з постраждалими від війни. Виїзні зустрічі по півдню. Безкоштовні консультації для родин військових.",
    joinedAt: "2023-01-20",
    eventsParticipated: [],
    activeCollections: [],
  },
  {
    id: "u6",
    name: "Олег Сухович",
    email: "oleg@dii.ua",
    avatar: av("Oleh"),
    role: "organizer",
    karma: 388,
    location: "Київ",
    bio: "Шеф-кухар. Готую сухпайки та консерви для фронту. Веду майстер-класи.",
    joinedAt: "2022-07-08",
    eventsParticipated: [],
    activeCollections: [],
  },
  {
    id: "u7",
    name: "Катерина Лисенко",
    email: "kateryna@dii.ua",
    avatar: av("Kateryna"),
    role: "volunteer",
    karma: 124,
    location: "Київ",
    bio: "Студентка медичного. Допомагаю з пакуванням аптечок, навчаюсь першій допомозі.",
    joinedAt: "2023-09-01",
    eventsParticipated: [],
    activeCollections: [],
  },
  {
    id: "u8",
    name: "Сергій Петренко",
    email: "serhiy@dii.ua",
    avatar: av("Serhiy"),
    role: "organizer",
    karma: 466,
    location: "Запоріжжя",
    bio: "Колишній військовий, тепер волонтер. Закупівлі техніки для підрозділів, перевірені канали.",
    joinedAt: "2022-05-19",
    eventsParticipated: [],
    activeCollections: [],
    verified: true,
  },
  {
    id: "u9",
    name: "Наталія Гриценко",
    email: "natalia@dii.ua",
    avatar: av("Natalia"),
    role: "volunteer",
    karma: 89,
    location: "Львів",
    bio: "Вчителька англійської. Працюю з дітьми ВПО — безкоштовні онлайн-уроки.",
    joinedAt: "2023-11-12",
    eventsParticipated: [],
    activeCollections: [],
  },
  {
    id: "u10",
    name: "Дмитро Кравченко",
    email: "dmytro@dii.ua",
    avatar: av("Dmytro"),
    role: "organizer",
    karma: 312,
    location: "Чернігів",
    bio: "IT-фахівець. Допомагаю діджиталізувати волонтерські процеси, веду збори на дрони.",
    joinedAt: "2022-09-03",
    eventsParticipated: [],
    activeCollections: [],
  },
];

const sampleComment = (
  id: string,
  userId: string,
  userName: string,
  avatarSeed: string,
  content: string,
  dAgo: number
) => ({
  id,
  userId,
  userName,
  userAvatar: av(avatarSeed),
  content,
  createdAt: daysAgo(dAgo),
});

const img = {
  food: "/posts/food.jpg",
  medical: "/posts/medical.jpg",
  hub: "/posts/hub.jpg",
  training: "/posts/training.jpg",
  drone: "/posts/drone.jpg",
  delivery: "/posts/delivery.jpg",
  nets: "/posts/nets.jpg",
  candles: "/posts/candles.jpg",
  psy: "/posts/psy.jpg",
  grant: "/posts/grant.jpg",
  thermal: "/posts/thermal.jpg",
  park: "/posts/park.jpg",
  safety: "/posts/safety.jpg",
  cook: "/posts/cook.jpg",
  school: "/posts/school.jpg",
  kids: "/posts/kids.jpg",
  blood: "/posts/blood.jpg",
  shelter: "/posts/shelter.jpg",
  pets: "/posts/pets.jpg",
  english: "/posts/english.jpg",
  warehouse: "/posts/warehouse.jpg",
  fundraiser: "/posts/fundraiser.jpg",
  veterans: "/posts/veterans.jpg",
  car: "/posts/car.jpg",
  ipads: "/posts/ipads.jpg",
  electricity: "/posts/electricity.jpg",
  art: "/posts/art.jpg",
  music: "/posts/music.jpg",
  sport: "/posts/sport.jpg",
  trauma: "/posts/trauma.jpg",
  generator: "/posts/generator.jpg",
  clothes: "/posts/clothes.jpg",
  books: "/posts/books.jpg",
  firstaid: "/posts/firstaid.jpg",
  volunteer_group: "/posts/volunteer_group.jpg",
  ukrainian_flag: "/posts/ukrainian_flag.jpg",
  toys: "/posts/toys.jpg",
  elderly: "/posts/elderly.jpg",
  demining: "/posts/demining.jpg",
  construction: "/posts/construction.jpg",
  tree: "/posts/tree.jpg",
  laptop_kids: "/posts/laptop_kids.jpg",
};

export const MOCK_POSTS: Post[] = [
  {
    id: "p1",
    type: "ПОДІЯ",
    title: "Збір продуктових наборів для переселенців у Броварах",
    description:
      "Приходь допомогти упакувати та роздати 500 продуктових наборів для родин ВПО. Потрібні руки та позитивний настрій!",
    content: `## Деталі події\n\nМи організовуємо масштабну акцію з роздачі продуктових наборів для внутрішньо переміщених осіб у Броварах.\n\n**Що потрібно зробити:**\n- Допомогти з розвантаженням машин (10:00–11:00)\n- Упакувати продуктові набори (11:00–13:00)\n- Роздати набори родинам (14:00–17:00)\n\n**Що взяти з собою:**\n- Зручний одяг\n- Воду та перекус\n- Хороший настрій\n\nУсе необхідне обладнання буде на місці.\n\n**Адреса:** вул. Незалежності, 15, Бровари`,
    date: "2026-06-15",
    location: "Бровари, Київська обл.",
    latitude: 50.50,
    longitude: 30.61,
    authorId: "u1",
    authorName: "Оксана Мельник",
    authorAvatar: av("Oksana"),
    status: "active",
    tags: ["продукти", "ВПО", "Бровари"],
    createdAt: daysAgo(10),
    image: img.food,
    maxParticipants: 30,
    currentParticipants: 18,
    comments: [
      sampleComment("c1", "u2", "Андрій Коваль", "Andriy",
        "Можу приїхати з авто — куди везти продукти?", 4),
      sampleComment("c2", "u1", "Оксана Мельник", "Oksana",
        "Андрій, дякую! Адреса складу: вул. Промислова, 8.", 4),
    ],
    bookings: [
      { id: "b1", userId: "u2", postId: "p1", status: "accepted", createdAt: daysAgo(9) },
      { id: "b2", userId: "u7", postId: "p1", status: "accepted", createdAt: daysAgo(8) },
    ],
  },
  {
    id: "p2",
    type: "ЗБІР",
    title: "Термінові ліки для 12-ї бригади — потрібно 85 000 грн",
    description:
      "Збираємо кошти на медикаменти першої необхідності: турнікети, бинти, знеболюючі та антибіотики для бійців.",
    content: `## Про збір\n\nНаша бригада потребує термінового поповнення медикаментів. Список погоджений з медслужбою.\n\n**Що купуємо:**\n- Турнікети CAT — 50 шт × 800 грн = 40 000 грн\n- Перев'язочні пакети — 200 шт × 120 грн = 24 000 грн\n- Знеболюючі (морфін, кеторол) — 21 000 грн\n\n**Разом: 85 000 грн**\n\nУсі чеки та фото-звіт публікуємо після закупівлі.`,
    date: "2026-06-20",
    location: "Донецький напрямок",
    latitude: 48.0,
    longitude: 37.0,
    authorId: "u1",
    authorName: "Оксана Мельник",
    authorAvatar: av("Oksana"),
    status: "urgent",
    tags: ["медицина", "армія", "терміново"],
    createdAt: daysAgo(8),
    image: img.medical,
    targetAmount: 85000,
    currentAmount: 61300,
    fundingLink: "https://send.monobank.ua/jar/example",
    featured: true,
    comments: [
      sampleComment("c3", "u3", "Марія Ткач", "Maria",
        "Як медик підтверджую — список правильний. Переказала 500 грн.", 3),
    ],
    bookings: [],
  },
  {
    id: "p3",
    type: "НОВИНА",
    title: "Відкрито новий хаб для волонтерів у центрі Києва",
    description:
      "На Подолі запрацював простір для координації волонтерської діяльності — координація, склад, відпочинок.",
    content: `## Волонтерський хаб на Подолі\n\nЗ 1 червня на вул. Спаській, 7 (Поділ, Київ) відкривається новий простір для волонтерів та організацій.\n\n**Що є в хабі:**\n- Переговорні кімнати\n- Склад для зберігання гуманітарки\n- Кухня та зона відпочинку\n- Wi-Fi та зарядні станції\n\n**Графік роботи:** Пн–Нд, 09:00–21:00\n\nПростір безкоштовний для зареєстрованих волонтерів.`,
    date: "2026-06-01",
    location: "Київ, Поділ",
    latitude: 50.50,
    longitude: 30.52,
    authorId: "u3",
    authorName: "Марія Ткач",
    authorAvatar: av("Maria"),
    status: "active",
    tags: ["Київ", "хаб", "новини"],
    createdAt: daysAgo(7),
    image: img.hub,
    comments: [],
    bookings: [],
  },
  {
    id: "p4",
    type: "ПОДІЯ",
    title: "Навчання першої медичної допомоги ТССС для волонтерів",
    description:
      "Безкоштовний тренінг з тактичної медицини — навчись рятувати життя в екстремальних ситуаціях.",
    content: `## Тренінг ТССС\n\nTactical Combat Casualty Care — стандарт медичної підготовки, прийнятий НАТО.\n\n**Програма:**\n- Теорія: оцінка обстановки, пріоритети допомоги\n- Практика: накладання турнікету, пакування ран\n- Відпрацювання сценаріїв\n\n**Тривалість:** 8 годин (10:00–18:00)\n**Локація:** тренінговий центр «Захист», вул. Велика Васильківська, 45, Київ`,
    date: "2026-06-22",
    location: "Київ",
    latitude: 50.45,
    longitude: 30.52,
    authorId: "u3",
    authorName: "Марія Ткач",
    authorAvatar: av("Maria"),
    status: "active",
    tags: ["медицина", "навчання", "ТССС", "Київ"],
    createdAt: daysAgo(6),
    image: img.training,
    maxParticipants: 20,
    currentParticipants: 7,
    comments: [],
    bookings: [],
  },
  {
    id: "p5",
    type: "ЗБІР",
    title: "Дрон FPV для розвідки — 45 000 грн",
    description:
      "Збираємо на FPV-дрон для розвідувального підрозділу. Чіткий список, звітність та фото передачі гарантовані.",
    content: `## Збір на FPV-дрон\n\nПідрозділ запросив модель DJI FPV Combo з дооснащенням.\n\n**Специфікація:**\n- DJI FPV Combo — 32 000 грн\n- Запасні пропелери + батареї — 8 000 грн\n- Кейс — 5 000 грн\n\n**Разом: 45 000 грн**`,
    date: "2026-07-01",
    location: "Запорізький напрямок",
    authorId: "u3",
    authorName: "Марія Ткач",
    authorAvatar: av("Maria"),
    status: "active",
    tags: ["дрон", "армія", "техніка"],
    createdAt: daysAgo(5),
    image: img.drone,
    targetAmount: 45000,
    currentAmount: 12500,
    fundingLink: "https://send.monobank.ua/jar/example2",
    comments: [],
    bookings: [],
  },
  {
    id: "p6",
    type: "НОВИНА",
    title: "Звіт: 3 000 пакунків гуманітарки доставлено на Херсонщину",
    description:
      "Завершено масштабну операцію з доставки гуманітарної допомоги у деокуповані райони Херсонської області.",
    content: `## Підсумки гуманітарної місії\n\nЗа два тижні роботи наша команда з 45 волонтерів доставила допомогу у 12 сіл Херсонської області.\n\n**Результати:**\n- 3 000 продуктових наборів\n- 800 гігієнічних наборів\n- 200 дитячих пакунків\n- 50 медичних аптечок\n\nДякуємо кожному, хто долучився!`,
    date: "2026-05-08",
    location: "Херсонська обл.",
    authorId: "u1",
    authorName: "Оксана Мельник",
    authorAvatar: av("Oksana"),
    status: "closed",
    tags: ["гуманітарка", "Херсон", "звіт"],
    createdAt: daysAgo(13),
    image: img.delivery,
    reportText: "Місія завершена. Усі пакунки доставлено за призначенням.",
    reportImages: [
      { url: img.delivery, caption: "Завантаження машин у Києві" },
      { url: img.warehouse, caption: "Сортування на складі" },
    ],
    comments: [],
    bookings: [],
  },
  {
    id: "p7",
    type: "ПОДІЯ",
    title: "Плетіння маскувальних сіток у Львові",
    description:
      "Щосереди та неділі плетемо маскувальні сітки для фронту. Долучайся будь-коли — навчимо на місці.",
    content: `## Плетіння сіток\n\nРегулярна активність — кожна середа та неділя, 14:00–19:00.\n\n**Адреса:** Будинок офіцерів, вул. Гвардійська, 10, Львів`,
    date: "2026-06-04",
    location: "Львів",
    latitude: 49.8397,
    longitude: 24.0297,
    authorId: "u2",
    authorName: "Андрій Коваль",
    authorAvatar: av("Andriy"),
    status: "active",
    tags: ["сітки", "Львів", "регулярно"],
    createdAt: daysAgo(4),
    image: img.nets,
    maxParticipants: 15,
    currentParticipants: 4,
    comments: [],
    bookings: [],
  },
  {
    id: "p8",
    type: "ЗБІР",
    title: "Окопні свічки — матеріали на 200 шт (8 000 грн)",
    description:
      "Виготовляємо окопні свічки. Збираємо на парафін, картон і консервні банки.",
    content: `## Окопні свічки для фронту\n\n**Що потрібно купити:**\n- Парафін (50 кг) — 4 500 грн\n- Картон гофрований — 1 500 грн\n- Банки металеві (200 шт) — 2 000 грн\n\n**Разом: 8 000 грн**`,
    date: "2026-06-30",
    location: "Дніпро",
    authorId: "u4",
    authorName: "Володимир Шевченко",
    authorAvatar: av("Volodymyr"),
    status: "active",
    tags: ["окопні свічки", "Дніпро"],
    createdAt: daysAgo(3),
    image: img.candles,
    targetAmount: 8000,
    currentAmount: 7200,
    fundingLink: "https://send.monobank.ua/jar/example3",
    comments: [],
    bookings: [],
  },
  {
    id: "p9",
    type: "ПОДІЯ",
    title: "Психологічна підтримка для родин військових — групова зустріч",
    description:
      "Безкоштовна групова сесія з психологом для дружин, матерів та дітей військовослужбовців.",
    content: `## Групова підтримка\n\nВедуча — Юлія Бондаренко, психолог з 8-річним досвідом.\n\n**Місце:** Центр родини, вул. Дерибасівська, 12, Одеса`,
    date: "2026-06-08",
    location: "Одеса",
    latitude: 46.4825,
    longitude: 30.7233,
    authorId: "u5",
    authorName: "Юлія Бондаренко",
    authorAvatar: av("Yulia"),
    status: "active",
    tags: ["психологія", "родини", "Одеса"],
    createdAt: daysAgo(2),
    image: img.psy,
    maxParticipants: 12,
    currentParticipants: 9,
    comments: [],
    bookings: [],
  },
  {
    id: "p10",
    type: "НОВИНА",
    title: "Платформа отримала грант від UNDP — 150 000 грн на розвиток",
    description:
      "Завдяки підтримці Програми розвитку ООН ми зможемо розширити функціонал та підтримати 50 нових організацій.",
    content: `## Грант UNDP\n\nРадо повідомляємо, що Дій став одним із 12 переможців конкурсу від UNDP.\n\n**На що йдуть кошти:**\n- Розробка мобільного застосунку\n- Інтеграція з банківськими API\n- Навчальні матеріали\n- Маркетинг у регіонах`,
    date: "2026-05-15",
    location: "Україна",
    authorId: "u4",
    authorName: "Володимир Шевченко",
    authorAvatar: av("Volodymyr"),
    status: "active",
    tags: ["грант", "UNDP", "розвиток"],
    createdAt: daysAgo(5),
    image: img.grant,
    comments: [],
    bookings: [],
  },
  {
    id: "p11",
    type: "ЗБІР",
    title: "Тепловізор Pulsar Helion для розвідки — 165 000 грн",
    description:
      "Збираємо на тепловізор для нічної розвідки. Підрозділ працює на нульовій лінії.",
    content: `## Тепловізор Pulsar Helion XQ50F\n\n**Розрахунок:**\n- Pulsar Helion XQ50F — 152 000 грн\n- Запасні батареї — 8 000 грн\n- Кейс + кронштейн — 5 000 грн\n\n**Разом: 165 000 грн**`,
    date: "2026-07-15",
    location: "Запорізький напрямок",
    authorId: "u8",
    authorName: "Сергій Петренко",
    authorAvatar: av("Serhiy"),
    status: "urgent",
    tags: ["тепловізор", "армія", "розвідка"],
    createdAt: daysAgo(2),
    image: img.thermal,
    targetAmount: 165000,
    currentAmount: 28400,
    fundingLink: "https://send.monobank.ua/jar/example4",
    comments: [],
    bookings: [],
  },
  {
    id: "p12",
    type: "ПОДІЯ",
    title: "Прибирання парку «Дружби народів» у Дніпрі",
    description:
      "Екологічна акція: збираємо сміття, висаджуємо саджанці, фарбуємо лавочки.",
    content: `## Робимо місто чистішим\n\n**План:**\n- 09:00–11:00 — реєстрація, видача інвентаря\n- 11:00–13:00 — прибирання за секторами\n- 13:00–14:00 — обід\n- 14:00–16:00 — висадка саджанців`,
    date: "2026-06-07",
    location: "Дніпро",
    authorId: "u4",
    authorName: "Володимир Шевченко",
    authorAvatar: av("Volodymyr"),
    status: "active",
    tags: ["екологія", "Дніпро", "родини"],
    createdAt: daysAgo(1),
    image: img.park,
    maxParticipants: 80,
    currentParticipants: 34,
    comments: [],
    bookings: [],
  },
  {
    id: "p13",
    type: "НОВИНА",
    title: "Як уникнути шахраїв під час донатів — 5 правил",
    description:
      "Кількість фейкових зборів зросла. Розповідаємо, як перевірити чесність кампанії за 2 хвилини.",
    content: `## 5 правил безпечного донату\n\n**1. Перевіряйте автора збору** — реальні волонтери мають історію.\n\n**2. Звертайте увагу на конкретику** — модель, кількість, ціни, підрозділ.\n\n**3. Перевіряйте банку** — ім'я в реквізитах має збігатись з організатором.\n\n**4. Шукайте звіти** — сумлінні волонтери публікують фото-звіти.\n\n**5. Питайте** — у коментарях. Якщо організатор уникає відповідей, не донатьте.`,
    date: "2026-05-19",
    location: "Україна",
    authorId: "u1",
    authorName: "Оксана Мельник",
    authorAvatar: av("Oksana"),
    status: "active",
    tags: ["безпека", "поради", "донати"],
    createdAt: daysAgo(1),
    image: img.safety,
    comments: [],
    bookings: [],
  },
  {
    id: "p14",
    type: "ПОДІЯ",
    title: "Майстер-клас з виготовлення сухпайків для бійців",
    description:
      "Готуємо домашні сухпайки за технологією шеф-кухаря з 10-річним досвідом. Все відправимо на фронт.",
    content: `## Домашні сухпайки\n\nШеф Олег Сухович навчить готувати концентровані поживні страви.\n\n**Меню зміни:**\n- Борщ-концентрат (50 порцій)\n- М'ясні рулети (30 порцій)\n- Енергетичні батончики (200 шт)`,
    date: "2026-06-12",
    location: "Київ",
    authorId: "u6",
    authorName: "Олег Сухович",
    authorAvatar: av("Oleh"),
    status: "active",
    tags: ["кулінарія", "сухпайки", "Київ"],
    createdAt: daysAgo(2),
    image: img.cook,
    maxParticipants: 18,
    currentParticipants: 11,
    comments: [],
    bookings: [],
  },
  {
    id: "p15",
    type: "ЗБІР",
    title: "Школа №27 у Бучі — ремонт класів (320 000 грн)",
    description:
      "Школа постраждала від обстрілів у 2022. Більшість відновлено, але 3 класи ще без вікон, дверей та меблів.",
    content: `## Відбудова школи №27\n\n**Розрахунок:**\n- Вікна металопластикові (12 шт) — 120 000 грн\n- Двері + ремонт — 60 000 грн\n- Парти + стільці — 95 000 грн\n- Дошки + проєктори — 45 000 грн`,
    date: "2026-08-15",
    location: "Буча, Київська обл.",
    latitude: 50.5569,
    longitude: 30.1997,
    authorId: "u1",
    authorName: "Оксана Мельник",
    authorAvatar: av("Oksana"),
    status: "active",
    tags: ["школа", "Буча", "освіта", "відбудова"],
    createdAt: daysAgo(0),
    image: img.school,
    targetAmount: 320000,
    currentAmount: 87500,
    fundingLink: "https://send.monobank.ua/jar/example5",
    comments: [],
    bookings: [],
  },
  {
    id: "p16",
    type: "ПОДІЯ",
    title: "Збір крові для постраждалих — Київ, ЦКЛ №1",
    description:
      "Гостро потрібна донорська кров I (+) та O (–). Здача займає 30 хв, гаряча їжа після.",
    content: `## Здавай кров — рятуй життя\n\nЦентральна міська лікарня №1 запрошує донорів.\n\n**Адреса:** вул. Анрі Барбюса, 5/2, Київ\n**Дні:** 18–22 червня, 09:00–14:00\n\n**Хто може здати:**\n- Вага > 50 кг\n- Не молодше 18 і не старше 60\n- Без застуди останні 14 днів`,
    date: "2026-06-18",
    location: "Київ",
    authorId: "u7",
    authorName: "Катерина Лисенко",
    authorAvatar: av("Kateryna"),
    status: "urgent",
    tags: ["донорство", "кров", "Київ", "медицина"],
    createdAt: daysAgo(0),
    image: img.blood,
    maxParticipants: 100,
    currentParticipants: 23,
    comments: [],
    bookings: [],
  },
  {
    id: "p17",
    type: "ЗБІР",
    title: "Ремонт укриття у школі №112, Харків (180 000 грн)",
    description:
      "Школа щодня вчиться у підвалі. Потрібно зробити нормальне освітлення, лавки, аптечку.",
    content: `## Облаштування укриття\n\nДіти проводять у підвалі до 4 годин щодня. Зараз там темно, холодно, без сидінь.\n\n**Що робимо:**\n- LED-освітлення + проводка — 60 000 грн\n- Лавки та столи — 45 000 грн\n- Утеплення стін — 50 000 грн\n- Аптечка + вогнегасники — 25 000 грн\n\n**Разом: 180 000 грн**`,
    date: "2026-07-30",
    location: "Харків",
    authorId: "u3",
    authorName: "Марія Ткач",
    authorAvatar: av("Maria"),
    status: "active",
    tags: ["укриття", "школа", "Харків"],
    createdAt: daysAgo(1),
    image: img.shelter,
    targetAmount: 180000,
    currentAmount: 42000,
    fundingLink: "https://send.monobank.ua/jar/example6",
    comments: [],
    bookings: [],
  },
  {
    id: "p18",
    type: "ПОДІЯ",
    title: "Притулок для тварин Ірпеня шукає вигульників",
    description:
      "Допоможи вигуляти 60 собак цієї суботи. Прогулянки 30 хв, інструктаж на місці.",
    content: `## День вигулу\n\nПритулок Sirius приймає волонтерів кожної суботи.\n\n**Адреса:** Ірпінь, вул. Тарасівська, 9\n**Час:** 10:00–16:00\n\nКожен волонтер працює з 2-3 собаками. Вода і чай надаються.`,
    date: "2026-06-14",
    location: "Ірпінь, Київська обл.",
    latitude: 50.5208,
    longitude: 30.2350,
    authorId: "u9",
    authorName: "Наталія Гриценко",
    authorAvatar: av("Natalia"),
    status: "active",
    tags: ["тварини", "притулок", "Ірпінь"],
    createdAt: daysAgo(2),
    image: img.pets,
    maxParticipants: 25,
    currentParticipants: 12,
    comments: [],
    bookings: [],
  },
  {
    id: "p19",
    type: "ПОДІЯ",
    title: "Безкоштовні онлайн-уроки англійської для дітей ВПО",
    description:
      "Шукаємо викладачів-волонтерів англійської (A1–B2) для онлайн-занять з дітьми переселенців.",
    content: `## Програма «English for Hope»\n\nЗа 6 місяців роботи долучили 240 дітей.\n\n**Що потрібно:**\n- 2 заняття на тиждень по 45 хв\n- Рівень C1 або вище\n- Зум, навушники, спокійне місце\n\nМатеріали надаємо. Координатор допомагає з організацією.`,
    date: "2026-06-25",
    location: "Онлайн",
    authorId: "u9",
    authorName: "Наталія Гриценко",
    authorAvatar: av("Natalia"),
    status: "active",
    tags: ["онлайн", "освіта", "англійська", "діти"],
    createdAt: daysAgo(3),
    image: img.english,
    maxParticipants: 30,
    currentParticipants: 14,
    comments: [],
    bookings: [],
  },
  {
    id: "p20",
    type: "ЗБІР",
    title: "Авто Mitsubishi L200 для евакуації — 425 000 грн",
    description:
      "Підрозділ просить пікап для евакуації поранених і доставки боєкомплекту. Працюємо з перевіреними каналами.",
    content: `## Авто для бригади\n\nЗнайшли Mitsubishi L200 2014 року в робочому стані.\n\n**Розрахунок:**\n- Авто — 380 000 грн\n- ТО + резина — 25 000 грн\n- Перереєстрація + маскування — 20 000 грн\n\n**Разом: 425 000 грн**\n\nПісля передачі публікую відео від екіпажу.`,
    date: "2026-08-01",
    location: "Покровський напрямок",
    authorId: "u8",
    authorName: "Сергій Петренко",
    authorAvatar: av("Serhiy"),
    status: "active",
    tags: ["авто", "евакуація", "армія"],
    createdAt: daysAgo(2),
    image: img.car,
    targetAmount: 425000,
    currentAmount: 156000,
    fundingLink: "https://send.monobank.ua/jar/example7",
    comments: [],
    bookings: [],
  },
  {
    id: "p21",
    type: "ЗБІР",
    title: "iPad-и для дистанційного навчання дітей ВПО (95 000 грн)",
    description:
      "Шукаємо 10 планшетів для дітей з прифронтових міст, які навчаються онлайн.",
    content: `## Планшети для навчання\n\nЦе спільний проєкт зі школою №25 у Запоріжжі.\n\n**Що купуємо:**\n- iPad 9-го покоління, 64GB — 10 шт × 9 500 = 95 000 грн\n\nПланшети передаємо родинам під розписку, на термін навчання.`,
    date: "2026-07-15",
    location: "Запоріжжя",
    latitude: 47.8388,
    longitude: 35.1396,
    authorId: "u10",
    authorName: "Дмитро Кравченко",
    authorAvatar: av("Dmytro"),
    status: "active",
    tags: ["освіта", "діти", "Запоріжжя"],
    createdAt: daysAgo(3),
    image: img.ipads,
    targetAmount: 95000,
    currentAmount: 38500,
    fundingLink: "https://send.monobank.ua/jar/example8",
    comments: [],
    bookings: [],
  },
  {
    id: "p22",
    type: "ПОДІЯ",
    title: "Розвантаження гумдопомоги — Чернігів, склад на Бобровиці",
    description:
      "Прибула фура з Польщі — 18 тонн. Потрібно 12 пар рук на 4 години роботи.",
    content: `## Розвантаження\n\n**Коли:** 13 червня, 09:00–13:00\n**Адреса:** Чернігів, Бобровиця, вул. Промислова, 4\n\nВажко фізично, але робота швидка. Вода, кава, обід — за наш рахунок.`,
    date: "2026-06-13",
    location: "Чернігів",
    latitude: 51.4982,
    longitude: 31.2893,
    authorId: "u10",
    authorName: "Дмитро Кравченко",
    authorAvatar: av("Dmytro"),
    status: "active",
    tags: ["розвантаження", "Чернігів", "склад"],
    createdAt: daysAgo(1),
    image: img.warehouse,
    maxParticipants: 12,
    currentParticipants: 5,
    comments: [],
    bookings: [],
  },
  {
    id: "p23",
    type: "НОВИНА",
    title: "Закрито збір: тепловізор передано підрозділу — звіт усередині",
    description:
      "Дякуємо 247 донорам — за 9 днів зібрали 165 000 грн. Тепловізор уже на позиціях.",
    content: `## Збір закрито\n\nЗа 9 днів спільно зібрали 165 240 грн (+240 запасу).\n\nТепловізор Pulsar Helion XQ50F закуплено, кейс та запасні батареї — також.\n\n**Передача:** 2 червня, особисто командиру взводу.\n\nВідео-звіт надсилаю тим, хто залишив контакт. Окреме «дякую» — Сергію за координацію.`,
    date: "2026-05-12",
    location: "Запорізький напрямок",
    authorId: "u8",
    authorName: "Сергій Петренко",
    authorAvatar: av("Serhiy"),
    status: "closed",
    tags: ["звіт", "тепловізор", "армія"],
    createdAt: daysAgo(7),
    image: img.thermal,
    reportText: "Збір закритий. Дякуємо всім.",
    reportImages: [
      { url: img.thermal, caption: "Передача тепловізора" },
    ],
    comments: [],
    bookings: [],
  },
  {
    id: "p24",
    type: "ЗБІР",
    title: "Генератор Honda 7 кВт для шпиталю (95 000 грн)",
    description:
      "Шпиталь у прифронтовому місті щодня працює на резерві. Потрібен потужніший генератор.",
    content: `## Генератор для шпиталю\n\nСтарий генератор уже не витримує — горить кожні 2 тижні.\n\n**Розрахунок:**\n- Honda EU70is, 7 кВт — 85 000 грн\n- Кабель + автомат — 6 000 грн\n- Доставка + установка — 4 000 грн\n\n**Разом: 95 000 грн**`,
    date: "2026-07-10",
    location: "Краматорськ",
    latitude: 48.7206,
    longitude: 37.5554,
    authorId: "u3",
    authorName: "Марія Ткач",
    authorAvatar: av("Maria"),
    status: "urgent",
    tags: ["генератор", "шпиталь", "Краматорськ"],
    createdAt: daysAgo(1),
    image: img.electricity,
    targetAmount: 95000,
    currentAmount: 17800,
    fundingLink: "https://send.monobank.ua/jar/example9",
    comments: [],
    bookings: [],
  },
  {
    id: "p25",
    type: "ПОДІЯ",
    title: "Артотерапія для дітей військових — Львів",
    description:
      "Майстер-клас з малювання для дітей 6–12 років з родин військових. Безкоштовно.",
    content: `## Артотерапія\n\nЗнаний львівський художник проводить виїзну майстерню.\n\n**Що буде:**\n- Малювання акварель та гуаш\n- Робота з кольорами емоцій\n- Спільна виставка робіт у кінці\n\n**Час:** 10:00–13:00\n**Адреса:** Палац мистецтв, Львів`,
    date: "2026-06-29",
    location: "Львів",
    latitude: 49.8397,
    longitude: 24.0297,
    authorId: "u5",
    authorName: "Юлія Бондаренко",
    authorAvatar: av("Yulia"),
    status: "active",
    tags: ["діти", "арт", "психологія", "Львів"],
    createdAt: daysAgo(4),
    image: img.art,
    maxParticipants: 20,
    currentParticipants: 8,
    comments: [],
    bookings: [],
  },
  {
    id: "p26",
    type: "ПОДІЯ",
    title: "Концерт «Музика підтримки» — Одеса, збір на дрони",
    description:
      "12 музикантів, 3 години сцени, усі донати — на FPV-дрони. Вхід вільний, донат бажаний.",
    content: `## «Музика підтримки»\n\nПроєкт об'єднав 12 виконавців з Одеси та Києва.\n\n**Дата:** 28 червня, 19:00\n**Локація:** Зелений театр, парк Шевченка\n\nУсі донати, зібрані під час концерту, спрямовуються на закупівлю FPV-дронів.`,
    date: "2026-06-28",
    location: "Одеса",
    latitude: 46.4825,
    longitude: 30.7233,
    authorId: "u5",
    authorName: "Юлія Бондаренко",
    authorAvatar: av("Yulia"),
    status: "active",
    tags: ["концерт", "Одеса", "дрони", "благодійність"],
    createdAt: daysAgo(5),
    image: img.music,
    maxParticipants: 300,
    currentParticipants: 87,
    comments: [],
    bookings: [],
  },
  {
    id: "p27",
    type: "ПОДІЯ",
    title: "Біг для героїв — благодійний забіг у Києві, 10 км",
    description:
      "Стартовий внесок 200 грн іде на реабілітацію поранених захисників. Старт о 09:00.",
    content: `## Біг для героїв\n\nДистанції: 5 км, 10 км, дитяча 500 м.\n\n**Дата:** 6 липня, 09:00\n**Старт:** ВДНГ, головна алея\n\nКожен учасник отримує футболку, медаль та сертифікат. Дитячі групи — окрема реєстрація.`,
    date: "2026-07-06",
    location: "Київ",
    authorId: "u1",
    authorName: "Оксана Мельник",
    authorAvatar: av("Oksana"),
    status: "active",
    tags: ["спорт", "Київ", "благодійність", "реабілітація"],
    createdAt: daysAgo(6),
    image: img.sport,
    maxParticipants: 500,
    currentParticipants: 124,
    comments: [],
    bookings: [],
  },
  {
    id: "p28",
    type: "ЗБІР",
    title: "Реабілітація бійця після ампутації — протез і фізіотерапія (480 000 грн)",
    description:
      "Андрію 27. Втратив ногу під Авдіївкою. Потрібен сучасний протез і курс реабілітації.",
    content: `## Допомога Андрію\n\nАндрій — стрілець, з фронту з січня 2024. Двічі поранений.\n\n**Розрахунок:**\n- Протез Ottobock C-Leg — 380 000 грн\n- Курс реабілітації (3 міс) — 80 000 грн\n- Транспорт і житло на період — 20 000 грн\n\n**Разом: 480 000 грн**\n\nДокументи від лікарні та військової частини в наявності.`,
    date: "2026-08-30",
    location: "Львів",
    latitude: 49.8397,
    longitude: 24.0297,
    authorId: "u4",
    authorName: "Володимир Шевченко",
    authorAvatar: av("Volodymyr"),
    status: "active",
    tags: ["реабілітація", "ветеран", "протез"],
    createdAt: daysAgo(8),
    image: img.veterans,
    targetAmount: 480000,
    currentAmount: 184000,
    fundingLink: "https://send.monobank.ua/jar/example10",
    comments: [],
    bookings: [],
  },
  {
    id: "p29",
    type: "ПОДІЯ",
    title: "Тренінг психологічної першої допомоги (PFA)",
    description:
      "За методикою ВООЗ. 1 день, 8 годин. Для тих, хто працює з постраждалими.",
    content: `## PFA — Psychological First Aid\n\nЦе не психотерапія. Це навички підтримки людини в перші години після травми.\n\n**Хто може долучитись:**\n- Волонтери\n- Соцпрацівники\n- Медики\n- Капелани\n\nСертифікати ВООЗ для тих, хто склав фінальний кейс.`,
    date: "2026-06-21",
    location: "Київ",
    authorId: "u5",
    authorName: "Юлія Бондаренко",
    authorAvatar: av("Yulia"),
    status: "active",
    tags: ["психологія", "PFA", "Київ", "навчання"],
    createdAt: daysAgo(2),
    image: img.trauma,
    maxParticipants: 25,
    currentParticipants: 17,
    comments: [],
    bookings: [],
  },
  {
    id: "p30",
    type: "НОВИНА",
    title: "Дій тепер у мобільному застосунку — beta для iOS",
    description:
      "Запустили beta-версію iOS-застосунку. Запрошуємо першу сотню тестерів — посилання всередині.",
    content: `## Мобільний застосунок\n\nMVP включає:\n- Стрічку\n- Заявки на події\n- Сповіщення\n- Профіль\n\n**Як долучитись до beta:** залиш email у формі — пришлемо TestFlight.\n\nAndroid версія — у червні.`,
    date: "2026-05-18",
    location: "Україна",
    authorId: "u4",
    authorName: "Володимир Шевченко",
    authorAvatar: av("Volodymyr"),
    status: "active",
    tags: ["продукт", "iOS", "beta"],
    createdAt: daysAgo(3),
    image: img.grant,
    comments: [],
    bookings: [],
  },
  {
    id: "p31",
    type: "ЗБІР",
    title: "Збір на ноутбук для дистанційного волонтерства (38 000 грн)",
    description:
      "Олені 16, вона веде наш TG-канал і робить графіку для зборів. Свого ноута немає.",
    content: `## Допомога Олені\n\nЇї поточний пристрій — старий планшет, який вже ледь тримає. На дизайн витрачає по 4-5 годин.\n\n**Що купуємо:** MacBook Air M2 13" — 38 000 грн.\n\nЯ — координатор, особисто куплю і передам, з чеками.`,
    date: "2026-07-05",
    location: "Київ",
    authorId: "u10",
    authorName: "Дмитро Кравченко",
    authorAvatar: av("Dmytro"),
    status: "active",
    tags: ["освіта", "техніка", "молодь"],
    createdAt: daysAgo(4),
    image: img.ipads,
    targetAmount: 38000,
    currentAmount: 11500,
    fundingLink: "https://send.monobank.ua/jar/example11",
    comments: [],
    bookings: [],
  },
  {
    id: "p32",
    type: "ПОДІЯ",
    title: "Велопробіг «На колесах для перемоги» — Київ → Чернігів",
    description:
      "100 км велопробігу за 2 дні. Збираємо донати по маршруту, ночівля в наметах.",
    content: `## Велопробіг\n\n**Маршрут:** Київ → Десна → Чернігів\n**Дата:** 19–20 липня\n**Дистанція:** 100 км (50/день)\n\nВечеря, намети — від організаторів. Учасники самі забезпечують велосипед і екіпіровку.`,
    date: "2026-07-19",
    location: "Київ → Чернігів",
    authorId: "u10",
    authorName: "Дмитро Кравченко",
    authorAvatar: av("Dmytro"),
    status: "active",
    tags: ["спорт", "велопробіг", "благодійність"],
    createdAt: daysAgo(6),
    image: img.sport,
    maxParticipants: 40,
    currentParticipants: 12,
    comments: [],
    bookings: [],
  },
  {
    id: "p33",
    type: "ЗБІР",
    title: "Генератор 5,5 кВт для прифронтової лікарні в Куп'янську",
    description:
      "Через постійні відключення лікарня залишається без живлення. Шукаємо інверторний генератор Honda EU65is.",
    content: `## Чому це критично\n\nЛікарня обслуговує 12 000 жителів і приймає поранених з фронтової лінії. Електрика — основа реанімації, операційних, ШВЛ.\n\n**Що купуємо:** Інверторний генератор 5,5 кВт (Honda EU65is) — 142 000 грн з доставкою та підключенням.\n\n**Чому інверторний?** Стабільна напруга для медобладнання, тихий, економний.\n\nЧеки публікуємо щотижня. Куратор — головлікар Олександр Гончар.`,
    date: "2026-06-25",
    location: "Куп'янськ, Харківська обл.",
    latitude: 49.7178,
    longitude: 37.6336,
    authorId: "u3",
    authorName: "Марія Ткач",
    authorAvatar: av("Maria"),
    status: "urgent",
    tags: ["генератор", "лікарня", "Куп'янськ", "медицина"],
    createdAt: daysAgo(2),
    image: img.generator,
    targetAmount: 142000,
    currentAmount: 87500,
    fundingLink: "https://send.monobank.ua/jar/example12",
    comments: [],
    bookings: [],
  },
  {
    id: "p34",
    type: "ПОДІЯ",
    title: "Сортування одягу для евакуйованих родин — склад у Львові",
    description:
      "Прийшло 4 фури з гуманітаркою з Польщі. Потрібно 15 людей на 3 дні сортування.",
    content: `## Що робимо\n\n- Розпакування коробок\n- Сортування за категоріями (чоловіче / жіноче / дитяче, сезонність)\n- Перевірка стану, пакування на видачу\n- Кросовки і взуття — окремо\n\n**Графік:** 28–30 червня, 9:00–17:00 (можна на один день).\n\nОбід забезпечуємо. Локація — склад на вул. Городоцькій 226.`,
    date: "2026-06-28",
    location: "Львів",
    latitude: 49.8397,
    longitude: 24.0297,
    authorId: "u2",
    authorName: "Андрій Коваль",
    authorAvatar: av("Andriy"),
    status: "active",
    tags: ["сортування", "одяг", "ВПО", "Львів"],
    createdAt: daysAgo(3),
    image: img.clothes,
    maxParticipants: 15,
    currentParticipants: 8,
    comments: [],
    bookings: [],
  },
  {
    id: "p35",
    type: "ЗБІР",
    title: "Підручники для дітей з прифронтових громад",
    description:
      "1200 дітей у 4 школах Донеччини залишилися без підручників. Збираємо 95 000 грн на повний комплект 5–9 клас.",
    content: `## Деталі\n\nЧерез обстріли та евакуацію — більшість шкільних матеріалів втрачено. Діти продовжують навчання у підвалах та сховищах.\n\n**Що купуємо:**\n- Українська мова та література — 350 шт\n- Математика — 350 шт\n- Історія України — 350 шт\n- Англійська мова — 350 шт\n\n**Партнер:** видавництво «Ранок» дає знижку 30%.\n**Доставка:** «Укрпошта», координує освітній відділ ОВА.`,
    date: "2026-08-25",
    location: "Донецька обл.",
    authorId: "u1",
    authorName: "Оксана Мельник",
    authorAvatar: av("Oksana"),
    status: "active",
    tags: ["діти", "освіта", "Донеччина", "школа"],
    createdAt: daysAgo(5),
    image: img.books,
    targetAmount: 95000,
    currentAmount: 41200,
    fundingLink: "https://send.monobank.ua/jar/example13",
    comments: [],
    bookings: [],
  },
  {
    id: "p36",
    type: "ПОДІЯ",
    title: "Курс тактичної медицини TCCC для цивільних",
    description:
      "8 годин практики: турнікети, тампонада, евакуація. Сертифікований інструктор.",
    content: `## Програма\n\n**День 1 (8 год):**\n- 09:00 — Теорія MARCH протоколу\n- 11:00 — Турнікети: накладання, фіксація, перевірка\n- 13:30 — Обід\n- 14:30 — Тампонада ран, оклюзійні пов'язки\n- 16:00 — Транспортування пораненого\n- 17:30 — Іспит, видача сертифікатів\n\n**Що отримуєте:**\n- Практичні навички\n- Міжнародний сертифікат TCCC-CLS\n- Базовий набір для аптечки (турнікет + бандаж)\n\n**Вартість для учасника:** 0 грн (фінансується нашим фондом).`,
    date: "2026-07-12",
    location: "Київ, вул. Володимирська 51",
    authorId: "u3",
    authorName: "Марія Ткач",
    authorAvatar: av("Maria"),
    status: "active",
    tags: ["навчання", "медицина", "TCCC", "Київ"],
    createdAt: daysAgo(4),
    image: img.firstaid,
    maxParticipants: 24,
    currentParticipants: 18,
    comments: [],
    bookings: [],
  },
  {
    id: "p37",
    type: "ПОДІЯ",
    title: "Концерт-благодійність на користь розмінування полів",
    description:
      "5 українських гуртів, всі збори — на гумздобробудуваня машин розмінування.",
    content: `## Лайнап\n\n- 19:00 — Open doors\n- 20:00 — Український гурт «Антитіла» (Live акустика)\n- 21:00 — KAZKA\n- 22:00 — ONUKA\n- 23:00 — DJ-set до 02:00\n\n**Квиток:** 500 грн (можна докинути більше).\n**Локація:** Палац спорту, вул. Велика Васильківська 55.\n\nУсі кошти йдуть на КрАЗ для розмінування з обладнанням Bozena 5.`,
    date: "2026-08-15",
    location: "Київ, Палац спорту",
    authorId: "u5",
    authorName: "Юлія Іваненко",
    authorAvatar: av("Yulia"),
    status: "active",
    tags: ["концерт", "благодійність", "розмінування", "Київ"],
    createdAt: daysAgo(8),
    image: img.music,
    maxParticipants: 2500,
    currentParticipants: 847,
    comments: [],
    bookings: [],
  },
  {
    id: "p38",
    type: "НОВИНА",
    title: "Платформа Дій нагороджена премією «Цифрова трансформація 2026»",
    description:
      "Дякуємо всім волонтерам, що довірились нам. За рік ми зробили це разом!",
    content: `## Підсумки року\n\nЗа 12 місяців роботи платформа об'єднала **18 600+ волонтерів** з 24 областей України:\n\n- **3 240** успішно проведених подій\n- **2 156 000 грн** зібрано на 412 зборах\n- **47** регіональних координаторів\n- **86%** довіра користувачів за результатами опитування\n\n**Дякуємо** Міністерству цифрової трансформації за визнання та нашій спільноті за щоденну роботу.\n\n**Що далі?**\n- Запуск регіональних офлайн-центрів у 5 містах\n- Інтеграція з Дія.Картка для прозорих донатів\n- Менторська програма для нових організаторів`,
    date: "2026-06-18",
    location: "Київ",
    authorId: "u1",
    authorName: "Оксана Мельник",
    authorAvatar: av("Oksana"),
    status: "active",
    tags: ["новини", "досягнення", "платформа"],
    createdAt: daysAgo(1),
    image: img.ukrainian_flag,
    featured: true,
    comments: [],
    bookings: [],
  },
  {
    id: "p39",
    type: "ПОДІЯ",
    title: "Майстер-клас «Як організувати збір» для новачків",
    description:
      "3 години практики: текст оголошення, бюджет, прозорість, як працювати з банкою.",
    content: `## Програма\n\n**1. Як написати оголошення (40 хв)**\n- Структура: проблема → рішення → бюджет\n- Що показувати, чого уникати\n- Приклади успішних і провальних кейсів\n\n**2. Бюджет і прозорість (60 хв)**\n- Як рахувати з ПДВ\n- Документи для звітів\n- Як показати чеки\n\n**3. Робота з банкою (40 хв)**\n- Monobank, Send.money\n- Картка ФОП vs приватна\n- Податки і дозвіл\n\n**4. Q&A (40 хв)**\n\n**Спікер:** Оксана Мельник — провела 47 зборів на 8.5 млн грн.`,
    date: "2026-07-08",
    location: "Київ, hub на вул. Хрещатик 22",
    authorId: "u1",
    authorName: "Оксана Мельник",
    authorAvatar: av("Oksana"),
    status: "active",
    tags: ["навчання", "організатори", "збори"],
    createdAt: daysAgo(7),
    image: img.training,
    maxParticipants: 30,
    currentParticipants: 22,
    comments: [],
    bookings: [],
  },
  {
    id: "p40",
    type: "ЗБІР",
    title: "Іграшки для дитячого хоспісу у Львові",
    description:
      "50 дітей з онкозахворюваннями чекають на свою радість. Збираємо 28 000 грн.",
    content: `## Кому це потрібно\n\nДитячий хоспіс «Подих» у Львові — це 50 дітей з онкологічними та паліативними діагнозами. Багатьом з них немає чим зайнятися — годинами лежать у палатах.\n\n**Що купуємо:**\n- Конструктори Lego — 15 наборів\n- Настільні ігри (Імаджинаріум, Манчкін) — 10 шт\n- М'які іграшки — 25 шт\n- Розмальовки + олівці — 50 наборів\n\nКуратор — психолог Олена Симоненко.`,
    date: "2026-07-01",
    location: "Львів",
    latitude: 49.8397,
    longitude: 24.0297,
    authorId: "u5",
    authorName: "Юлія Іваненко",
    authorAvatar: av("Yulia"),
    status: "active",
    tags: ["діти", "хоспіс", "Львів", "іграшки"],
    createdAt: daysAgo(3),
    image: img.toys,
    targetAmount: 28000,
    currentAmount: 22400,
    fundingLink: "https://send.monobank.ua/jar/example14",
    comments: [],
    bookings: [],
  },
  {
    id: "p41",
    type: "ПОДІЯ",
    title: "Відвідування самотніх літніх людей у Запоріжжі",
    description:
      "Раз на тиждень навідуємо 18 бабусь і дідусів. Просто поговорити, допомогти з покупками.",
    content: `## Що робимо\n\nКожної суботи відвідуємо літніх людей у 4 будинках Бородинського мікрорайону. Багато з них втратили родичів через війну або переселилися самі.\n\n**Що потрібно від вас:**\n- 3-4 години у суботу (10:00–14:00)\n- Бажання вислухати\n- Можна допомогти з продуктами (за бажанням)\n\nЯ та ще 4 волонтери ходимо групами по 2. Я познайомлю з підопічними.\n\n**Не потрібно:** грошей, спецнавичок.`,
    date: "2026-06-21",
    location: "Запоріжжя",
    authorId: "u8",
    authorName: "Дмитро Шевчук",
    authorAvatar: av("Dmytro"),
    status: "active",
    tags: ["літні", "соцдопомога", "Запоріжжя"],
    createdAt: daysAgo(6),
    image: img.elderly,
    maxParticipants: 12,
    currentParticipants: 5,
    comments: [],
    bookings: [],
  },
  {
    id: "p42",
    type: "НОВИНА",
    title: "Як вибрати надійний збір: 5 ознак прозорості",
    description:
      "Швидкий гайд від експерта: на що звертати увагу, перш ніж жертвувати кошти.",
    content: `## 5 ознак прозорого збору\n\n**1. Чіткий бюджет**\nНе «допоможіть, що зможете», а конкретні позиції з цінами. Приклад: «турнікет CAT × 50 шт = 35 000 грн».\n\n**2. Особа організатора відома**\nФото профілю, ім'я, місто, попередні збори. Анонім — червоний прапор (виключення — окремі військові частини).\n\n**3. Деталізована мета**\nЗнаєте, КОМУ потрібна допомога: яка частина, лікарня, родина (з посиланнями на офіційні джерела).\n\n**4. Регулярні звіти**\nЩотижня або після ключових покупок — фото чеків, фото переданого.\n\n**5. Розумна сума**\nЯкщо «5 турнікетів за 500 тис грн» — це підозріло. Перевіряйте середні ціни.\n\n---\n\nЯкщо хочете передати кошти, але збір викликає сумніви — пишіть нам у підтримку.`,
    date: "2026-06-12",
    location: "Україна",
    authorId: "u3",
    authorName: "Марія Ткач",
    authorAvatar: av("Maria"),
    status: "active",
    tags: ["гайд", "прозорість", "збори", "поради"],
    createdAt: daysAgo(2),
    image: img.fundraiser,
    comments: [],
    bookings: [],
  },
  {
    id: "p43",
    type: "ПОДІЯ",
    title: "Толока з відновлення дитячого майданчика після обстрілу",
    description:
      "Київщина, селище Андріївка. Збираємо інструменти, фарбу, дошки — і робимо все за вихідні.",
    content: `## Що потрібно зробити\n\nДитячий майданчик у Андріївці постраждав восени 2024. Місцева громада зібрала кошти, ми — руки.\n\n**Графік:**\n- Субота 9:00 — демонтаж пошкодженого\n- Субота 13:00 — обід (від громади)\n- Субота 14:00–18:00 — встановлення нових елементів\n- Неділя 9:00–14:00 — фарбування, благоустрій\n- Неділя 15:00 — урочисте відкриття\n\n**Беремо з собою:** робочий одяг, рукавиці, добрий настрій.\n**Інструмент і матеріали:** забезпечуємо.`,
    date: "2026-07-26",
    location: "Андріївка, Київська обл.",
    latitude: 50.5300,
    longitude: 30.1900,
    authorId: "u1",
    authorName: "Оксана Мельник",
    authorAvatar: av("Oksana"),
    status: "active",
    tags: ["толока", "діти", "відновлення", "Київщина"],
    createdAt: daysAgo(9),
    image: img.construction,
    maxParticipants: 25,
    currentParticipants: 16,
    comments: [],
    bookings: [],
  },
  {
    id: "p44",
    type: "ЗБІР",
    title: "Ноутбуки для дистанційного навчання у школах Херсонщини",
    description:
      "120 дітей з зруйнованих сіл навчаються онлайн без техніки. Збираємо 380 000 грн.",
    content: `## Проблема\n\n4 школи в звільнених громадах Херсонщини знаходяться у напівзруйнованому стані. Діти ходять у школи в інших селах, але деякі — на дистанційці без жодної техніки.\n\n**Що купуємо:**\n- 20 ноутбуків Acer Aspire 3 (бюджетні, але нові) — 380 000 грн\n- Безкоштовний інтернет — забезпечує Київстар\n\n**Розподіл:** школи самі визначають, кому передати, контроль через освітній відділ ОВА.\n\n**Гарантія:** 2 роки + страхування від крадіжки.`,
    date: "2026-09-01",
    location: "Херсонська обл.",
    latitude: 46.6537,
    longitude: 32.6178,
    authorId: "u4",
    authorName: "Володимир Бойко",
    authorAvatar: av("Volodymyr"),
    status: "active",
    tags: ["освіта", "техніка", "Херсонщина", "діти"],
    createdAt: daysAgo(11),
    image: img.laptop_kids,
    targetAmount: 380000,
    currentAmount: 145000,
    fundingLink: "https://send.monobank.ua/jar/example15",
    comments: [],
    bookings: [],
  },
  {
    id: "p45",
    type: "НОВИНА",
    title: "Звіт: як ми витратили 5 млн грн за пів року",
    description:
      "Повна розшифровка кожної категорії витрат: дрони, медицина, евакуація, освіта.",
    content: `## Звіт за 6 місяців (січень — червень 2026)\n\n**Загалом зібрано:** 5 142 800 грн\n**Витрачено:** 4 987 200 грн (на рахунку залишається 155 600 для поточних зборів)\n\n### Категорії витрат\n\n**Медицина — 1 856 000 грн (37%)**\n- Турнікети, аптечки IFAK: 720 000\n- Ліки, інфузія: 412 000\n- Тактична медицина (курси): 184 000\n- Реабілітаційне обладнання: 540 000\n\n**Дрони і РЕБ — 1 245 000 грн (25%)**\n- Mavic 3 Pro × 8 шт: 720 000\n- Аналоги Autel × 5 шт: 285 000\n- Антени, РЕБ: 240 000\n\n**Евакуація — 825 000 грн (17%)**\n- Паливо для авто: 412 000\n- Ремонт мікроавтобусів: 285 000\n- Запчастини: 128 000\n\n**Освіта дітей — 612 000 грн (12%)**\n- Підручники: 287 000\n- Канцтовари: 95 000\n- Шкільне харчування ВПО: 230 000\n\n**ВПО і гуманітарка — 449 200 грн (9%)**\n- Продуктові набори: 285 000\n- Засоби гігієни: 88 000\n- Дитяче харчування: 76 200\n\n---\n\nУсі чеки доступні в нашому Notion: link.dii.ua/zvit-2026.\n\nДякуємо вам за довіру 💙💛`,
    date: "2026-07-01",
    location: "Україна",
    authorId: "u1",
    authorName: "Оксана Мельник",
    authorAvatar: av("Oksana"),
    status: "active",
    tags: ["звіт", "прозорість", "статистика"],
    createdAt: daysAgo(0),
    image: img.grant,
    featured: true,
    comments: [],
    bookings: [],
  },
  {
    id: "p46",
    type: "ПОДІЯ",
    title: "Тернопільський благодійний ярмарок для переселенців",
    description:
      "Запрошуємо на ярмарок місцевих виробників: усе зібране йде на допомогу переселенцям Тернопільщини.",
    content: `## Благодійний ярмарок у Тернополі

**Дата:** 18 червня 2026
**Час:** 11:00–17:00
**Місце:** Площа Героїв Євромайдану, Тернопіль

На ярмарку будуть:
- локальні виробники їжі та сувенірів
- зона для дітей з майстер-класами
- виступи волонтерських гуртів

Усі кошти будуть спрямовані на придбання продуктів та гігієни для ВПО, що мешкають у регіоні.

**Як допомогти:**
- придбати вироби на ярмарку
- стати волонтером при роздачі
- поширювати інформацію серед друзів`,
    date: "2026-06-18",
    location: "Тернопіль",
    latitude: 49.5535,
    longitude: 25.5948,
    authorId: "u1",
    authorName: "Оксана Мельник",
    authorAvatar: av("Oksana"),
    status: "active",
    tags: ["Тернопіль", "ярмарок", "переселенці", "гуманітарка"],
    createdAt: daysAgo(0),
    image: img.fundraiser,
    maxParticipants: 40,
    currentParticipants: 12,
    comments: [],
    bookings: [],
  },
];

export const MOCK_DONATIONS: Donation[] = [
  {
    id: "d1",
    postId: "p2",
    userId: "u3",
    userName: "Марія Ткач",
    userAvatar: av("Maria"),
    amount: 500,
    message: "Дякую за роботу!",
    createdAt: daysAgo(3),
  },
  {
    id: "d2",
    postId: "p2",
    userId: "u2",
    userName: "Андрій Коваль",
    userAvatar: av("Andriy"),
    amount: 1000,
    createdAt: daysAgo(2),
  },
  {
    id: "d3",
    postId: "p8",
    userId: "u5",
    userName: "Юлія Бондаренко",
    userAvatar: av("Yulia"),
    amount: 800,
    message: "Хай горять довше.",
    createdAt: daysAgo(1),
  },
  {
    id: "d4",
    postId: "p15",
    userId: "u9",
    userName: "Наталія Гриценко",
    userAvatar: av("Natalia"),
    amount: 2000,
    createdAt: daysAgo(0),
  },
  {
    id: "d5",
    postId: "p28",
    userId: "u1",
    userName: "Оксана Мельник",
    userAvatar: av("Oksana"),
    amount: 5000,
    message: "Сил тобі і швидкого одужання!",
    createdAt: daysAgo(2),
  },
];
